# Generated by Django 2.0 on 2019-10-08 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(6, message='用户名最短不能少于6位')])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6, message='密码最短不能少于6位')])),
                ('telephone', models.CharField(max_length=11)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_model',
                'ordering': ['-pub_date'],
            },
        ),
    ]
